### ISSUE TITLE
Gem doesn't appear to be setting timezone in rails

### ISSUE THREAD

**Issue by mhuggins** [kbaum/browser-timezone-rails#2]
I'm trying to use this gem (ruby 1.9.3p448, rails 3.2.14), and I think I have it set up correctly, but I'm not seeing the `Time.zone` change in my controller action that's depending on it.

I've added this to my Gemfile (along with running `bundle install` and restarting my server):

    gem 'browser-timezone-rails'

I've added this to my application.js:

    //= require browser_timezone_rails/application

I'm setting a breakpoint in my controller's update action, where my params include form data with user-submitted date/time info that I'm trying to localize.  Inspecting within my breakpoint, I see the following:

    cookies['browser.timezone']   # => "America/Denver"
    Time.zone                     # => (GMT+00:00) UTC
    Time.zone.now                 # => Mon, 30 Sep 2013 20:17:08 UTC +00:00

My Rails app's default zone is UTC, and it appears that the gem isn't overriding that by the time my controller action is being hit.  Also, inspecting `caller` from my controller action, I'd expect to see the around_filter `set_time_zone` method somewhere in the stack, but it's not appearing.  (`messages_controller.rb` is my controller file.)

```
=> ["/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/pry-0.9.12.2/lib/pry/pry_instance.rb:328:in `eval'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/pry-0.9.12.2/lib/pry/pry_instance.rb:328:in `evaluate_ruby'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/pry-0.9.12.2/lib/pry/pry_instance.rb:278:in `re'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/pry-0.9.12.2/lib/pry/pry_instance.rb:254:in `rep'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/pry-0.9.12.2/lib/pry/pry_instance.rb:234:in `block (3 levels) in repl'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/pry-0.9.12.2/lib/pry/pry_instance.rb:232:in `loop'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/pry-0.9.12.2/lib/pry/pry_instance.rb:232:in `block (2 levels) in repl'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/pry-0.9.12.2/lib/pry/pry_instance.rb:231:in `catch'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/pry-0.9.12.2/lib/pry/pry_instance.rb:231:in `block in repl'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/pry-0.9.12.2/lib/pry/pry_instance.rb:230:in `catch'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/pry-0.9.12.2/lib/pry/pry_instance.rb:230:in `repl'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/pry-0.9.12.2/lib/pry/pry_class.rb:170:in `start'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/pry-debugger-0.2.2/lib/pry-debugger/pry_ext.rb:15:in `block in start_with_pry_debugger'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/pry-debugger-0.2.2/lib/pry-debugger/processor.rb:18:in `block in run'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/pry-debugger-0.2.2/lib/pry-debugger/processor.rb:17:in `catch'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/pry-debugger-0.2.2/lib/pry-debugger/processor.rb:17:in `run'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/pry-debugger-0.2.2/lib/pry-debugger/pry_ext.rb:14:in `start_with_pry_debugger'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/pry-0.9.12.2/lib/pry/core_extensions.rb:43:in `pry'",
 "/Users/mhuggins/Development/pcrt-web/app/controllers/admin/messages_controller.rb:19:in `create'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/actionpack-3.2.14/lib/action_controller/metal/implicit_render.rb:4:in `send_action'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/actionpack-3.2.14/lib/abstract_controller/base.rb:167:in `process_action'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/actionpack-3.2.14/lib/action_controller/metal/rendering.rb:10:in `process_action'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/actionpack-3.2.14/lib/abstract_controller/callbacks.rb:18:in `block in process_action'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/activesupport-3.2.14/lib/active_support/callbacks.rb:414:in `_run__814835236786761717__process_action__4531372456997062722__callbacks'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/activesupport-3.2.14/lib/active_support/callbacks.rb:405:in `__run_callback'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/activesupport-3.2.14/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/activesupport-3.2.14/lib/active_support/callbacks.rb:81:in `run_callbacks'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/actionpack-3.2.14/lib/abstract_controller/callbacks.rb:17:in `process_action'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/actionpack-3.2.14/lib/action_controller/metal/rescue.rb:29:in `process_action'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/actionpack-3.2.14/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/activesupport-3.2.14/lib/active_support/notifications.rb:123:in `block in instrument'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/activesupport-3.2.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/activesupport-3.2.14/lib/active_support/notifications.rb:123:in `instrument'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/actionpack-3.2.14/lib/action_controller/metal/instrumentation.rb:29:in `process_action'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/actionpack-3.2.14/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/activerecord-3.2.14/lib/active_record/railties/controller_runtime.rb:18:in `process_action'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/actionpack-3.2.14/lib/abstract_controller/base.rb:121:in `process'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/actionpack-3.2.14/lib/abstract_controller/rendering.rb:45:in `process'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/actionpack-3.2.14/lib/action_controller/metal.rb:203:in `dispatch'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/actionpack-3.2.14/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/actionpack-3.2.14/lib/action_controller/metal.rb:246:in `block in action'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:73:in `call'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:36:in `call'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:608:in `call'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/better_errors-0.3.2/lib/better_errors/middleware.rb:51:in `app_call'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/better_errors-0.3.2/lib/better_errors/middleware.rb:45:in `call'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/actionpack-3.2.14/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/rack-1.4.5/lib/rack/etag.rb:23:in `call'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/rack-1.4.5/lib/rack/conditionalget.rb:35:in `call'",
 "/Users/mhuggins/.rvm/gems/ruby-1.9.3-p448@pcrt/gems/actionpack-3.2.14/lib/action_dispatch/middleware/head.rb:14:in `call'",
```

Any idea of what I may be doing wrong?  Thanks!

**Comment by kbaum** [comment]
Closing as this was addressed years ago 😄
